name: Docker Image CI

on:
  release:
    inputs:
      tag:
        default: $(date +%s)
        required: true
        description: Tag for image
        type: string
  workflow_call:
    inputs:
      tag:
        default: $(date +%s)
        required: true
        description: Tag for image
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hello-oxie:$[[ inputs.tag ]]
