name: Initial workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run the workflow against"
        type: environment
        required: true
  push:
    branches:
      - "**"

jobs:
  init: 
    name: Init the workflow
    if: ${{ inputs.environment == '' }}
    uses: oxie-inc/scripts/.github/workflows/init.yml@main
  deploy-website:
    name: Deploy Image Package
    uses: ./.github/workflows/deploy-image.yml
    needs: init
    if: ${{ !cancelled() && (needs.init.result == 'skipped' || success() && github.ref_name == 'main') }}